### ISSUE TITLE
User avatar feature

### ISSUE THREAD

**Issue by bigint** [kinopio-club/kinopio-help#25]
It would be great if we have a user avatar instead of just colors!

**Comment by pketh** [comment]
hopefully something I can do in the future, thx :)

**Comment by pketh** [comment]
with more thought: 

someone recently asked a similar question in the community discord chat https://discord.com/channels/857305113936134204/857724063903252530/877206768965517363 , and I don't think I'll have user avatars because the advantage of colored avatars only is:

- easy to set up and change
- matches your user with your paint and selection color during collaboration
- distinct from other social sites where profile attractiveness might affect how you're seen
